import type { Metadata } from "next";
import type { Locale } from "@/lib/i18n";
import { SITE_URL } from "@/lib/siteUrl";

/** Brand strings reused by metadata and structured data. */
export const SITE_NAME = "MyPet.ge";
export const SITE_TITLE_TEMPLATE = "%s · MyPet.ge";
export const TWITTER_HANDLE = "@mypetge";

/** Social / official profiles — also emitted as `sameAs` in structured data. */
export const SITE_PROFILES = ["https://t.me/mypetge"];

/** The card generated by `app/opengraph-image.tsx`, as an absolute URL. */
export const OG_IMAGE_URL = `${SITE_URL}/opengraph-image`;

/**
 * The square brand mark (`public/logo.png`), as an absolute URL.
 *
 * Distinct from OG_IMAGE_URL on purpose: structured data wants an actual logo,
 * and Google rejects a wide social card in `Organization.logo` — it expects
 * something close to square that it can crop into a knowledge panel.
 */
export const LOGO_URL = `${SITE_URL}/logo.png`;
export const LOGO_SIZE = 512;

/**
 * Default social card, restated explicitly on every page.
 *
 * The root `opengraph-image.tsx` file convention cannot be relied on to flow
 * down: metadata from nested segments is merged *shallowly*, so a page that
 * defines `openGraph` at all replaces the root's entire `openGraph` object —
 * image included. Leaving `images` unset therefore ships a card with no
 * picture, not an inherited one.
 */
const DEFAULT_OG_IMAGE = {
  url: OG_IMAGE_URL,
  width: 1200,
  height: 630,
  alt: "MyPet.ge — pet listings and services in Georgia",
};

/**
 * Search-console ownership tokens for the root layout's `verification` field.
 *
 * Read from the environment rather than hardcoded: a token is per-property and
 * gets re-issued when a property is removed and re-added, so it must not need a
 * deploy of new code. Google Search Console is what actually gets the site
 * crawled promptly and reports what it thinks of the pages — the site is
 * invisible until a property is verified, and the file-upload method does not
 * survive a redeploy, so the meta tag is the durable option.
 *
 * Returns undefined when nothing is configured so no empty tag ships.
 */
export function siteVerification(): Metadata["verification"] | undefined {
  const google = process.env.GOOGLE_SITE_VERIFICATION?.trim();
  const yandex = process.env.YANDEX_VERIFICATION?.trim();
  // Bing/IndexNow's own tag has no dedicated Next field; `other` emits it raw.
  const bing = process.env.BING_SITE_VERIFICATION?.trim();

  if (!google && !yandex && !bing) return undefined;
  return {
    ...(google ? { google } : {}),
    ...(yandex ? { yandex } : {}),
    ...(bing ? { other: { "msvalidate.01": bing } } : {}),
  };
}

function ogLocale(locale: Locale) {
  return locale === "en" ? "en_US" : "ka_GE";
}

function ogAlternateLocale(locale: Locale) {
  return locale === "en" ? "ka_GE" : "en_US";
}

export interface PageMetadataInput {
  locale: Locale;
  title: string;
  description: string;
  /** Absolute path, e.g. "/buy-sell". Used for the canonical + og:url. */
  path: string;
  keywords?: string[];
  /** Absolute image URLs (listing/business photos). Falls back to the site OG image. */
  images?: string[];
  type?: "website" | "article";
  /** Set for pages that must never enter the index (e.g. a missing record). */
  noIndex?: boolean;
  /**
   * Skip the root's "%s · MyPet.ge" title template. Only the homepage needs
   * this — its title already leads with the brand, so the template would
   * render "MyPet.ge — … · MyPet.ge".
   */
  absoluteTitle?: boolean;
}

/**
 * One place that assembles canonical URL + OpenGraph + Twitter for every page,
 * so a section page can't accidentally ship half a card. `metadataBase` is set
 * once in the root layout, so relative paths here resolve to absolute URLs.
 */
export function pageMetadata({
  locale,
  title,
  description,
  path,
  keywords,
  images,
  type = "website",
  noIndex = false,
  absoluteTitle = false,
}: PageMetadataInput): Metadata {
  const ownImages = images?.length ? images.slice(0, 4) : undefined;
  const ogImages = ownImages
    ? ownImages.map((url) => ({ url }))
    : [DEFAULT_OG_IMAGE];

  return {
    // og:title and twitter:title always take the plain string — the template
    // is a `<title>`-only concern.
    title: absoluteTitle ? { absolute: title } : title,
    description,
    ...(keywords?.length ? { keywords } : {}),
    alternates: { canonical: path },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
    openGraph: {
      type,
      siteName: SITE_NAME,
      url: `${SITE_URL}${path === "/" ? "" : path}`,
      title,
      description,
      locale: ogLocale(locale),
      alternateLocale: ogAlternateLocale(locale),
      images: ogImages,
    },
    twitter: {
      card: "summary_large_image",
      site: TWITTER_HANDLE,
      creator: TWITTER_HANDLE,
      title,
      description,
      images: ownImages ?? [OG_IMAGE_URL],
    },
  };
}

const first = (v: string | string[] | undefined) => (Array.isArray(v) ? v[0] : v);

/**
 * Metadata for a filterable browse route (/buy-sell, /adoption, …).
 *
 * Two things these pages need beyond `pageMetadata`:
 *  - page 2+ gets a self-referencing canonical and a numbered title, so the
 *    pages don't all collapse into one duplicate of page 1;
 *  - a free-text search (`?q=`) is a thin, infinitely-variable result page —
 *    those are kept out of the index and the canonical points back at the
 *    clean section URL.
 */
export function browsePageMetadata({
  locale,
  title,
  description,
  path,
  keywords,
  searchParams,
  pageWord,
}: Omit<PageMetadataInput, "type" | "noIndex" | "images"> & {
  searchParams: Record<string, string | string[] | undefined>;
  /** Localized word for "page", used in the page-2+ title. */
  pageWord: string;
}): Metadata {
  const pageNum = Number(first(searchParams.page));
  const page = Number.isInteger(pageNum) && pageNum > 1 ? pageNum : 1;
  const isSearch = Boolean(first(searchParams.q));

  const base = pageMetadata({
    locale,
    title: page > 1 ? `${title} — ${pageWord} ${page}` : title,
    description,
    path: page > 1 && !isSearch ? `${path}?page=${page}` : path,
    keywords,
    noIndex: isSearch,
  });

  return base;
}
