import type { Metadata } from "next";
import type { Locale } from "@/lib/i18n";
import { SITE_URL } from "@/lib/siteUrl";

/** Brand strings reused by metadata and structured data. */
export const SITE_NAME = "MyPet.ge";
export const SITE_TITLE_TEMPLATE = "%s · MyPet.ge";
export const TWITTER_HANDLE = "@mypetge";

/** Social / official profiles — also emitted as `sameAs` in structured data. */
export const SITE_PROFILES = ["https://t.me/mypetge"];

/**
 * The social card itself is generated by `app/opengraph-image.tsx` and is
 * attached automatically to every route that doesn't declare its own images —
 * so pages leave `openGraph.images` unset to inherit it. This URL exists only
 * for structured data (`Organization.logo`), which needs a concrete address.
 */
export const OG_IMAGE_URL = `${SITE_URL}/opengraph-image`;

function ogLocale(locale: Locale) {
  return locale === "en" ? "en_US" : "ka_GE";
}

function ogAlternateLocale(locale: Locale) {
  return locale === "en" ? "ka_GE" : "en_US";
}

export interface PageMetadataInput {
  locale: Locale;
  title: string;
  description: string;
  /** Absolute path, e.g. "/buy-sell". Used for the canonical + og:url. */
  path: string;
  keywords?: string[];
  /** Absolute image URLs (listing/business photos). Falls back to the site OG image. */
  images?: string[];
  type?: "website" | "article";
  /** Set for pages that must never enter the index (e.g. a missing record). */
  noIndex?: boolean;
}

/**
 * One place that assembles canonical URL + OpenGraph + Twitter for every page,
 * so a section page can't accidentally ship half a card. `metadataBase` is set
 * once in the root layout, so relative paths here resolve to absolute URLs.
 */
export function pageMetadata({
  locale,
  title,
  description,
  path,
  keywords,
  images,
  type = "website",
  noIndex = false,
}: PageMetadataInput): Metadata {
  // Omit `images` entirely when the page has none of its own: that lets the
  // root `opengraph-image` file convention supply the card (with correct
  // width/height/type) instead of us restating a bare URL.
  const ogImages = images?.length ? images.slice(0, 4) : undefined;

  return {
    title,
    description,
    ...(keywords?.length ? { keywords } : {}),
    alternates: { canonical: path },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
    openGraph: {
      type,
      siteName: SITE_NAME,
      url: `${SITE_URL}${path === "/" ? "" : path}`,
      title,
      description,
      locale: ogLocale(locale),
      alternateLocale: ogAlternateLocale(locale),
      ...(ogImages ? { images: ogImages.map((url) => ({ url })) } : {}),
    },
    twitter: {
      card: "summary_large_image",
      site: TWITTER_HANDLE,
      creator: TWITTER_HANDLE,
      title,
      description,
      ...(ogImages ? { images: ogImages } : {}),
    },
  };
}

const first = (v: string | string[] | undefined) => (Array.isArray(v) ? v[0] : v);

/**
 * Metadata for a filterable browse route (/buy-sell, /adoption, …).
 *
 * Two things these pages need beyond `pageMetadata`:
 *  - page 2+ gets a self-referencing canonical and a numbered title, so the
 *    pages don't all collapse into one duplicate of page 1;
 *  - a free-text search (`?q=`) is a thin, infinitely-variable result page —
 *    those are kept out of the index and the canonical points back at the
 *    clean section URL.
 */
export function browsePageMetadata({
  locale,
  title,
  description,
  path,
  keywords,
  searchParams,
  pageWord,
}: Omit<PageMetadataInput, "type" | "noIndex" | "images"> & {
  searchParams: Record<string, string | string[] | undefined>;
  /** Localized word for "page", used in the page-2+ title. */
  pageWord: string;
}): Metadata {
  const pageNum = Number(first(searchParams.page));
  const page = Number.isInteger(pageNum) && pageNum > 1 ? pageNum : 1;
  const isSearch = Boolean(first(searchParams.q));

  const base = pageMetadata({
    locale,
    title: page > 1 ? `${title} — ${pageWord} ${page}` : title,
    description,
    path: page > 1 && !isSearch ? `${path}?page=${page}` : path,
    keywords,
    noIndex: isSearch,
  });

  return base;
}
